// Provincias de Argentina y localidades de Neuquén y Río Negro para el
// selector de "¿De dónde son?" de la inscripción (ver
// app/components/location-fields.tsx). Neuquén y Río Negro van primero
// porque son de donde viene casi toda la Liga; para esas dos se elige la
// localidad de una lista (sin errores de tipeo → se pueden agrupar después),
// para el resto se escribe a mano.
//
// Las listas cubren municipios, comisiones de fomento y los parajes más
// habituales. Si falta alguna, el selector tiene "Otra localidad" para
// escribirla — y alcanza con agregarla acá.

export const PRIORITY_PROVINCES = ["Neuquén", "Río Negro"] as const;

export const OTHER_PROVINCES = [
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Ciudad Autónoma de Buenos Aires",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
] as const;

export const ALL_PROVINCES: readonly string[] = [...PRIORITY_PROVINCES, ...OTHER_PROVINCES];

const NEUQUEN_LOCALITIES = [
  "Aguada San Roque",
  "Aluminé",
  "Andacollo",
  "Añelo",
  "Arroyito",
  "Bajada del Agrio",
  "Barrancas",
  "Buta Ranquil",
  "Caviahue-Copahue",
  "Centenario",
  "Chorriaca",
  "Chos Malal",
  "Covunco Abajo",
  "Coyuco-Cochico",
  "Cutral Có",
  "El Cholar",
  "El Huecú",
  "El Sauce",
  "Guañacos",
  "Huinganco",
  "Junín de los Andes",
  "Las Coloradas",
  "Las Lajas",
  "Las Ovejas",
  "Loncopué",
  "Los Catutos",
  "Los Chihuidos",
  "Los Miches",
  "Manzano Amargo",
  "Mariano Moreno",
  "Moquehue",
  "Neuquén",
  "Octavio Pico",
  "Paso Aguerre",
  "Picún Leufú",
  "Piedra del Águila",
  "Pilo Lil",
  "Plaza Huincul",
  "Plottier",
  "Quili Malal",
  "Ramón M. Castro",
  "Rincón de los Sauces",
  "San Martín de los Andes",
  "San Patricio del Chañar",
  "Santo Tomás",
  "Sauzal Bonito",
  "Senillosa",
  "Taquimilán",
  "Tricao Malal",
  "Varvarco",
  "Villa Curí Leuvú",
  "Villa del Nahueve",
  "Villa El Chocón",
  "Villa La Angostura",
  "Villa Pehuenia",
  "Villa Traful",
  "Vista Alegre",
  "Zapala",
];

const RIO_NEGRO_LOCALITIES = [
  "Aguada Cecilio",
  "Aguada de Guerra",
  "Aguada Guzmán",
  "Allen",
  "Arroyo Los Berros",
  "Balneario El Cóndor",
  "Balsa Las Perlas",
  "Barda del Medio",
  "Campo Grande",
  "Catriel",
  "Cerro Policía",
  "Cervantes",
  "Chelforó",
  "Chichinales",
  "Chimpay",
  "Chipauquil",
  "Choele Choel",
  "Cinco Saltos",
  "Cipolletti",
  "Clemente Onelli",
  "Colan Conhué",
  "Colonia Juliá y Echarren",
  "Comallo",
  "Cona Niyeu",
  "Contralmirante Cordero",
  "Coronel Belisle",
  "Darwin",
  "Dina Huapi",
  "El Bolsón",
  "El Caín",
  "El Cuy",
  "El Manso",
  "Fernández Oro",
  "General Conesa",
  "General Enrique Godoy",
  "General Roca",
  "Guardia Mitre",
  "Ingeniero Huergo",
  "Ingeniero Jacobacci",
  "Laguna Blanca",
  "Lamarque",
  "Las Grutas",
  "Los Menucos",
  "Luis Beltrán",
  "Mainqué",
  "Mallín Ahogado",
  "Mamuel Choique",
  "Maquinchao",
  "Mencué",
  "Nahuel Niyeu",
  "Naupa Huen",
  "Ñorquincó",
  "Ojos de Agua",
  "Peñas Blancas",
  "Pichi Mahuida",
  "Pilcaniyeu",
  "Pilquiniyeu del Limay",
  "Playas Doradas",
  "Pomona",
  "Prahuaniyeu",
  "Ramos Mexía",
  "Río Chico",
  "Río Colorado",
  "San Antonio Oeste",
  "San Carlos de Bariloche",
  "San Javier",
  "Sargento Vidal",
  "Sierra Colorada",
  "Sierra Grande",
  "Sierra Pailemán",
  "Valcheta",
  "Viedma",
  "Villa Alberdi",
  "Villa Llanquín",
  "Villa Manzano",
  "Villa Regina",
  "Yaminué",
];

/** Localidades para elegir de una lista — solo Neuquén y Río Negro. Para el
 * resto de las provincias devuelve null (se escribe a mano). */
export function localitiesForProvince(province: string | null | undefined): readonly string[] | null {
  if (province === "Neuquén") return NEUQUEN_LOCALITIES;
  if (province === "Río Negro") return RIO_NEGRO_LOCALITIES;
  return null;
}

/** "Plaza Huincul, Neuquén" — para mostrar. Vacío si no hay nada cargado. */
export function formatLocation(locality: string | null | undefined, province: string | null | undefined): string {
  return [locality, province].filter(Boolean).join(", ");
}
